//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElaneDaneshgah
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_exception
    {
        public int id { get; set; }
        public int id_term { get; set; }
        public string date { get; set; }
        public Nullable<int> classroomID { get; set; }
        public string Start_time { get; set; }
        public string end_time { get; set; }
        public string Description { get; set; }
    
        public virtual tb_classroom tb_classroom { get; set; }
        public virtual tb_term tb_term { get; set; }
    }
}
