//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElaneDaneshgah
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_teacher
    {
        public tb_teacher()
        {
            this.tb_teacher_course = new HashSet<tb_teacher_course>();
            this.tb_term = new HashSet<tb_term>();
        }
    
        public string id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<tb_teacher_course> tb_teacher_course { get; set; }
        public virtual ICollection<tb_term> tb_term { get; set; }
    }
}
