//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElaneDaneshgah
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_teacher_course
    {
        public int id { get; set; }
        public string teacherID { get; set; }
        public int courseID { get; set; }
    
        public virtual tb_teacher tb_teacher { get; set; }
        public virtual tbl_course tbl_course { get; set; }
    }
}
